#!/bin/bash

while true; do

	dwmweather > /home/dacian/.local/bin/dwmblocks/dwmweather.txt
	dwmupdates > /home/dacian/.local/bin/dwmblock/dwmupdates.txt

	sleep 3600s

done &

while true; do

	WEATHER=$(< /home/dacian/.local/bin/dwmblocks/dwmweather.txt)
	CPU=$(dwmcpu)
	MEM=$(dwmmemory)
	NET=$(dwmnet)
	TEMP=$(dwmtemp)
	HDD=$(dwmdisk)
	UPDATES=$(< /home/dacian/.local/bin/swmblocks/dwmupdates.txt)
	TIME=$(dwmclock)
	xsetroot -name "| $WEATHER | $CPU | $MEM | $NET | $TEMP | $HDD | $UPDATES | $TIME"

	sleep 5s
	
done &
